# Generated by Django 5.0 on 2025-12-05 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_nombre', models.CharField(max_length=200)),
                ('dest_ramo', models.CharField(blank=True, max_length=200)),
                ('dest_domicilio_laboral', models.CharField(max_length=300)),
                ('dest_cp', models.CharField(max_length=20)),
                ('dest_localidad', models.CharField(max_length=200)),
                ('dest_provincia', models.CharField(max_length=200)),
                ('rem_nombre', models.CharField(max_length=200)),
                ('rem_dni', models.CharField(max_length=20)),
                ('rem_fecha', models.CharField(max_length=20)),
                ('rem_domicilio_real', models.CharField(max_length=300)),
                ('rem_cp', models.CharField(max_length=20)),
                ('rem_localidad', models.CharField(max_length=200)),
                ('rem_provincia', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('tipo_comunicacion', models.CharField(choices=[('renuncia', 'Comunicación de renuncia'), ('ausencia', 'Comunicación de ausencia'), ('otro', 'Otro tipo de comunicación')], max_length=20)),
                ('font_destinatario', models.IntegerField(default=12)),
                ('font_remitente', models.IntegerField(default=12)),
                ('font_cuerpo', models.IntegerField(default=12)),
                ('font_tipo', models.IntegerField(default=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegrams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
